#!/usr/bin/python

try:
    # generate an exception
    cliff = asdfasdfasdf

except:
    print 'we had an exception, re raise'
    raise

finally:
    print 'finally block'



